workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: "archlinux:latest"

.default-before-script:
  before_script:
    - pacman-key --init
    - pacman -Syu --needed --noconfirm just mkcert

.with-rust:
  before_script:
    - !reference [".default-before-script", "before_script"]
    - pacman -Syu --needed --noconfirm rust just gcc
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - .cargo/bin
      - .cargo/registry/index
      - .cargo/registry/cache
      - target/debug/deps
      - target/debug/build
      - target/release/deps
      - target/release/build
  variables:
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:
  - check
  - build

licenses:
  stage: check
  extends: .default-before-script
  script:
    - pacman -Syu --needed --noconfirm reuse
    - just licenses

check-dependencies:
  stage: check
  extends: .with-rust
  script:
    - pacman -Syu --needed --noconfirm cargo-deny
    - just check-dependencies

format:
  stage: check
  extends: .with-rust
  script:
    - just lint

test:
  tags:
    # the test suite needs to spawn podman containers, so we run this job in a VM
    - vm
  stage: check
  extends: .with-rust
  variables:
    RUST_LOG: debug
  script:
    - pacman -Syu --needed --noconfirm cargo-nextest podman jq geckodriver firefox
    - just test

build-release:
  stage: build
  extends: .with-rust
  artifacts:
    paths:
      - target/release/backend
  script:
    - just build-release

push-container-image:
  tags:
    # we build containers so it's easier to do this in a VM
    - vm
  stage: build
  extends: .default-before-script
  needs: ["build-release"]
  script:
    - pacman -Syu --needed --noconfirm podman
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - just build-release-container-image
    - podman push buildbtw "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
