workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: "archlinux:latest"

.default-before-script:
  before_script:
    - pacman -Syu --needed --noconfirm just

.with-rust:
  before_script:
    - !reference [".default-before-script", "before_script"]
    # Use rustup instead of rust package so we can
    # install the nightly toolchain alongside stable
    - pacman -Syu --needed --noconfirm rustup just gcc
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - .cargo/bin
      - .cargo/registry/index
      - .cargo/registry/cache
      - target/debug/deps
      - target/debug/build
      - target/release/deps
      - target/release/build
  variables:
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:
  - check

reuse:
  stage: check
  extends: .default-before-script
  script:
    - pacman -Syu --needed --noconfirm reuse
    - just licenses

deny:
  stage: check
  extends: .with-rust
  script:
    - rustup install stable
    - pacman -Syu --needed --noconfirm cargo-deny
    - just deny

format:
  stage: check
  extends: .with-rust
  script:
    - rustup install nightly
    - just format
