[package]
name = "buildbtw"
version = "0.0.5"
description = "A service for building packages"
authors = [
    "Levente Polyak <anthraxx@archlinux.org>",
    "Rafael Epplée <raffomania@archlinux.org>",
    "Sven-Hendrik Haase <svenstaro@archlinux.org>",
]
edition = "2024"
homepage = "https://gitlab.archlinux.org/archlinux/buildbtw"
keywords = ["arch", "linux", "packaging", "archlinux", "ci"]
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://gitlab.archlinux.org/archlinux/buildbtw"
publish = false

[[bin]]
name = "buildbtw-backend"
path = "src/bin/backend/main.rs"

[[bin]]
name = "buildbtw-executor"
path = "src/bin/executor/main.rs"

[profile.release]
codegen-units = 1
lto = true

# Lints that are "warn" will be fine in development,
# but the CI will reject them.
# "forbid" cannot be overridden, e.g. with an inline comment.
[lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
todo = "warn"
unimplemented = "warn"
dbg_macro = "warn"
pedantic = { level = "warn", priority = -1 }
# Sometimes, `to_string` is more expressive than `clone`.
implicit_clone = "allow"
# Lots of false positives.
doc_markdown = "allow"
# This would be too verbose for application code.
missing_errors_doc = "allow"
unnecessary_debug_formatting = "allow"
implicit_hasher = "allow"
large_enum_variant = "allow"

[features]
sea-orm-debug-print = ["sea-orm/debug-print"]

[dependencies]
alpm-srcinfo = "0.6.3"
alpm-types = "0.11.2"
asynk-strim = "0.1.5"
clap = { version = "4.6.0", features = ["cargo", "derive", "env", "wrap_help"] }
color-eyre = "0.6"
console-subscriber = "0.5.0"
datastar = { version = "0.3.1", features = ["axum", "tracing"] }
directories = "6.0.0"
gitlab = "0.1811.0"
redact = { version = "0.1.11", features = ["serde"] }
reqwest = { version = "0.13.2", features = ["json", "stream", "query"] }
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = { version = "1.0.149", features = ["raw_value"] }
strum = { version = "0.28.0", features = ["derive"] }
tera = "1.20.1"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = [
    "fs",
    "macros",
    "process",
    "rt-multi-thread",
    "tracing",
    "signal",
] }
tokio-util = "0.7.18"
toml = "1.1.0"
time = { version = "0.3.47", features = ["formatting", "parsing", "serde"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
url = "2.5.8"
sea-orm = { version = "2.0.0-rc.37", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
    "with-time",
    "with-json",
    "with-uuid",
    "sqlite-use-returning-for-3_35",
], default-features = false }
sea-orm-migration = { version = "2.0.0-rc.37", features = [
    "runtime-tokio-rustls",
    "sqlx-sqlite",
], default-features = false }
camino = "1.2.2"
axum = { version = "0.8.8", features = [
    "macros",
    "tracing",
    "tokio",
    "json",
    "query",
    "http1",
    "http2",
], default-features = false }
tower-http = { version = "0.6.8", features = [
    "timeout",
    "fs",
], default-features = false }
axum-extra = { version = "0.12.5", features = [
    "routing",
    "typed-routing",
    "typed-header",
    "cookie-private",
] }
uuid = { version = "1.22.0", features = ["v4", "serde"] }
nutype = { version = "0.7.0", features = [
    "derive_unchecked",
    "serde",
    "regex",
] }
regex = "1.12.3"
rust-embed = { version = "8.11.0", features = [
    "deterministic-timestamps",
    "include-exclude",
] }
openidconnect = { version = "4.0.1", features = [
    "timing-resistant-secret-traits",
] }
garde = { version = "0.23", features = ["derive"] }
listenfd = "1.0.2"
graphql_client = "0.14.0"
derive_more = { version = "2.1.1", features = [
    "as_ref",
    "display",
    "into_iterator",
    "from",
    "from_str",
] }
git2 = { version = "0.21", default-features = false, features = ["ssh"] }
petgraph = "0.8.3"
tempfile = "3.27.0"
colored = "3.1.1"
webbrowser = { version = "1.2.0", features = ["hardened", "disable-wsl"] }
tracing-error = "0.2.1"
named-lock = "0.4.1"
port_check = "0.3.0"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
rustls = { version = "0.23.39", features = ["aws-lc-rs"] }
serde_with = "3.20.0"
yansi = { version = "1.0.1", features = ["detect-env", "detect-tty"] }
futures = "0.3.32"
ssh-key = { version = "0.6.7", default-features = false, features = ["ecdsa", "std"] }

[dev-dependencies]
axum-test = { version = "20.0.0", features = ["typed-routing"] }
thirtyfour = { version = "0.37.0", features = [
    "rustls",
], default-features = false }
rstest = { version = "0.26.1", default-features = false }
cookie = "0.18.1"
temp-env = "0.3.6"
