[package]
name = "buildbtw"
authors = [
    "Levente Polyak <anthraxx@archlinux.org>",
    "Rafael Epplée <raffomania@archlinux.org>",
    "Sven-Hendrik Haase <svenstaro@archlinux.org>",
]
edition = "2024"
homepage = "https://gitlab.archlinux.org/archlinux/buildbtw"
keywords = ["arch", "linux", "packaging", "ci", "building", "graph"]
license = "GPL-3.0-or-later"
repository = "https://gitlab.archlinux.org/archlinux/buildbtw"

[profile.release]
codegen-units = 1
lto = true
debug = true

# Lints that are "warn" will be fine in development,
# but the CI will reject them.
# "forbid" cannot be overridden, e.g. with an inline comment.
[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
missing_debug_implementations = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
variant_size_differences = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
todo = "warn"
unimplemented = "warn"
dbg_macro = "warn"
print_stdout = "warn"
print_stderr = "warn"

[dependencies]
alpm-srcinfo = { git = "https://gitlab.archlinux.org/archlinux/alpm/alpm.git", branch = "main" }
alpm-types = { git = "https://gitlab.archlinux.org/archlinux/alpm/alpm.git", branch = "main" }
clap = { version = "4.5.42", features = [
    "cargo",
    "derive",
    "env",
    "wrap_help",
] }
color-eyre = "0.6"
colored = "3.0.0"
console-subscriber = "0.4.1"
directories = "6.0.0"
gitlab = "0.1802.0"
redact = "0.1.11"
reqwest = { version = "0.12.22", features = [
    "json",
    "stream",
    "rustls-tls",
], default-features = false }
rstest = "0.26.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = { version = "1.0.141", features = ["raw_value"] }
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = [
    "fs",
    "macros",
    "process",
    "rt-multi-thread",
    "tracing",
] }
toml = "0.9.4"
time = { version = "0.3.41", features = ["formatting", "parsing", "serde"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"
sea-orm = { version = "1.1.14", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
    "with-time",
    "with-json",
    "with-uuid",
    "debug-print",
], default-features = false }
sea-orm-migration = { version = "1.1.14", features = [
    "runtime-tokio-rustls",
    "sqlx-sqlite",
], default-features = false }
camino = "1.1.11"
