FROM docker.io/library/archlinux:base
COPY --chmod=755 buildbtw-server-poc /app/buildbtw-server-poc
RUN pacman -Syu --noconfirm openssh libgit2
WORKDIR /app/data
CMD ["ssh-agent", "bash", "-c", "ssh-add /ssh_id; /app/buildbtw-server-poc run"]
