#!/bin/bash
set -o nounset -o errexit -o pipefail -o xtrace

echo "Pulling image..."
podman pull registry.archlinux.org/archlinux/buildbtw:poc-server-latest
echo "Starting container..."
podman run \
    --env-file /srv/buildbtw/env \
    --restart always \
    --detach \
    --replace --name server \
    --volume /srv/buildbtw/data:/app/data \
    --publish 127.0.0.1:8080:8080 \
    registry.archlinux.org/archlinux/buildbtw:poc-server-latest \
    run